server:
  port: 8002
  servlet:
    context-path: /asset
spring:
  application:
    name: eastcom-ripple-asset-management      #Micro service name
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.93.10:33061/eastcom_ripple?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/eastcom_ripple?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: eastcom

#mybatis-plus configuration
mybatis-plus:
  mapper-locations: classpath:com/eastcom/ripple/mapper/**/*Mapper.xml
  type-aliases-package: com.eastcom.ripple.entity,;com.eastcom.ripple.dto,;com.eastcom.ripple.vo
  configuration:
    #open LowerCamelCase naming transformation
    map-underscore-to-camel-case: true

#pagehelper configuration
pagehelper:
  helper-dialect: mysql
  reasonable: true

#showSql
logging:
  level:
    com.eastcom.ripple.mapper: debug