server:
  port: 9001
  servlet:
    context-path: /meetingroom

spring:
  application:
    name: eastcom-ripple-meeting-room-management      #Micro service name
  datasource:
    url: jdbc:mysql://192.168.93.10:33061/eastcom_ripple?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: eastcom
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus configuration
mybatis-plus:
  mapper-locations: classpath:com/eastcom/ripple/mapper/*Mapper.xml
  type-aliases-package: com.eastcom.ripple.entity
  configuration:
    #open LowerCamelCase naming transformation
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com.eastcom.ripple.mapper: debug
